import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { BrandLogo } from "@/components/BrandLogo";
import { FigmaSvg } from "@/components/FigmaSvg";
import { figmaAssets } from "@/figmaAssets";
import { colors, fonts, radii } from "@/theme";

function SummaryCard({ title, value, note, accent }: { title: string; value: string; note: string; accent?: boolean }) {
  return <View style={styles.summaryCard}><Text style={styles.summaryTitle}>{title}</Text><Text style={[styles.summaryValue, accent && styles.accentValue]}>{value}</Text><Text style={styles.summaryNote}>{note}</Text></View>;
}
function Shortcut({ icon, label, onPress }: { icon: string; label: string; onPress?: () => void }) {
  return <Pressable style={styles.shortcut} onPress={onPress}><View style={styles.shortcutIcon}><FigmaSvg uri={icon} width={20} height={20} /></View><Text style={styles.shortcutLabel}>{label}</Text></Pressable>;
}
function NavItem({ icon, label, active, onPress }: { icon: string; label: string; active?: boolean; onPress?: () => void }) {
  return <Pressable onPress={onPress} style={styles.navItem}><FigmaSvg uri={icon} width={24} height={24} /><Text style={[styles.navLabel, active && styles.navActive]}>{label}</Text></Pressable>;
}

export default function TenantHomeReviewScreen() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.logo}><BrandLogo /></View>
      <View style={styles.header}><View style={styles.notification}><FigmaSvg uri={figmaAssets.bell} width={20} height={20} /></View><View style={styles.greeting}><Text style={styles.greetingTitle}>سلام، علی رضایی</Text><Text style={styles.greetingNote}>به چارخونه خوش آمدید.</Text></View></View>
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <View style={styles.grid}><View style={styles.row}><SummaryCard title="میزان قابل تأمین" value="۴۵۰ میلیون تومان" note="براساس شرایط فعلی" /><SummaryCard title="اعتبار شما" value="خوب" note="براساس سابقه شما" /></View><View style={styles.row}><SummaryCard title="وضعیت قرارداد" value="در انتظار بررسی" note="قرارداد خودنویس ثبت‌شده" accent /><SummaryCard title="پرداخت بعدی" value="۱۵ مهر ۱۴۰۵" note="۱۸٬۵۰۰٬۰۰۰ تومان" accent /></View></View>
        <View style={styles.actionCard}><Text style={styles.actionTitle}>اقدام بعدی شما</Text><Text style={styles.actionText}>برای ادامه فرایند، شرایط تأمین مالی را بررسی کنید یا کد رهگیری قرارداد خودنویس را ثبت کنید.</Text><View style={styles.actionRow}><Pressable style={styles.outlineButton} onPress={() => router.push("/(shared)/contract-tracking")}><Text style={styles.outlineText}>ثبت کد رهگیری</Text></Pressable><Pressable style={styles.primaryButton} onPress={() => router.push("/(tenant)/calculator")}><Text style={styles.primaryText}>محاسبه شرایط</Text></Pressable></View></View>
        <View style={styles.membershipCard}><View style={styles.membershipHeader}><View style={styles.activeBadge}><Text style={styles.activeText}>فعال</Text></View><Text style={styles.membershipTitle}>عضویت چارخونه</Text></View><View style={styles.membershipRow}><Text style={styles.membershipValue}>تا ۵۰۰٬۰۰۰٬۰۰۰ تومان</Text><Text style={styles.membershipLabel}>سقف تأمین مالی</Text></View><View style={styles.membershipRow}><Text style={styles.membershipValue}>۱ بار</Text><Text style={styles.membershipLabel}>دفعات باقی‌مانده</Text></View></View>
        <Text style={styles.quickTitle}>دسترسی سریع</Text>
        <View style={styles.quickRow}><Shortcut icon={figmaAssets.calculator} label="ماشین‌حساب" onPress={() => router.push("/(tenant)/calculator")} /><Shortcut icon={figmaAssets.wallet} label="دریافت و پرداخت" onPress={() => router.push("/(tenant)/payments")} /><Shortcut icon={figmaAssets.file} label="قراردادها" onPress={() => router.push("/(shared)/contracts")} /><Shortcut icon={figmaAssets.home} label="املاک من" /></View>
        <View style={styles.notice}><Text style={styles.noticeText}>درخواست شما پس از تکمیل مراحل برای بررسی به بانک ارسال می‌شود.</Text><FigmaSvg uri={figmaAssets.info} width={16} height={16} /></View>
      </ScrollView>
      <View style={styles.bottomNav}><NavItem icon={figmaAssets.user} label="حساب من" onPress={() => router.push("/(shared)/profile")} /><NavItem icon={figmaAssets.fileText} label="قراردادها" onPress={() => router.push("/(shared)/contracts")} /><NavItem icon={figmaAssets.creditCard} label="دریافت و پرداخت" onPress={() => router.push("/(tenant)/payments")} /><NavItem icon={figmaAssets.homeActive} label="خانه" active /></View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.primary }, logo: { height: 60, alignItems: "flex-end" }, header: { height: 56, paddingHorizontal: 20, paddingVertical: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, notification: { width: 40, height: 40, borderRadius: radii.md, alignItems: "center", justifyContent: "center" }, greeting: { alignItems: "flex-end", gap: 2 }, greetingTitle: { color: colors.page, fontFamily: fonts.semibold, fontSize: 16, writingDirection: "rtl" }, greetingNote: { color: colors.muted, fontFamily: fonts.regular, fontSize: 12, writingDirection: "rtl" },
  scroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16, gap: 20 }, grid: { gap: 12 }, row: { flexDirection: "row", gap: 12 }, summaryCard: { flex: 1, minHeight: 109, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: 16, gap: 8, alignItems: "flex-end" }, summaryTitle: { color: colors.primary, fontFamily: fonts.bold, fontSize: 12, writingDirection: "rtl" }, summaryValue: { width: "100%", color: colors.primary, fontFamily: fonts.regular, fontSize: 14, textAlign: "right", writingDirection: "rtl" }, accentValue: { color: colors.accent }, summaryNote: { width: "100%", color: colors.muted, fontFamily: fonts.regular, fontSize: 11, textAlign: "right", writingDirection: "rtl" },
  actionCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.lg, padding: 20, gap: 16 }, actionTitle: { color: colors.primary, fontFamily: fonts.semibold, fontSize: 16, textAlign: "right", writingDirection: "rtl" }, actionText: { color: colors.muted, fontFamily: fonts.regular, fontSize: 13, lineHeight: 22, textAlign: "right", writingDirection: "rtl" }, actionRow: { flexDirection: "row", gap: 12 }, outlineButton: { flex: 1, height: 48, borderRadius: radii.md, borderWidth: 1.5, borderColor: colors.primary, alignItems: "center", justifyContent: "center" }, primaryButton: { flex: 1, height: 48, borderRadius: radii.md, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, outlineText: { color: colors.primary, fontFamily: fonts.medium, fontSize: 14, writingDirection: "rtl" }, primaryText: { color: colors.surface, fontFamily: fonts.medium, fontSize: 14, writingDirection: "rtl" },
  membershipCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, padding: 16, gap: 12 }, membershipHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, activeBadge: { backgroundColor: colors.successSoft, borderRadius: radii.sm, paddingHorizontal: 12, paddingVertical: 6 }, activeText: { color: colors.primary, fontFamily: fonts.medium, fontSize: 12, writingDirection: "rtl" }, membershipTitle: { color: colors.primary, fontFamily: fonts.semibold, fontSize: 14, writingDirection: "rtl" }, membershipRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, membershipValue: { color: colors.primary, fontFamily: fonts.regular, fontSize: 13, writingDirection: "rtl" }, membershipLabel: { color: colors.muted, fontFamily: fonts.regular, fontSize: 13, writingDirection: "rtl" },
  quickTitle: { color: colors.page, fontFamily: fonts.semibold, fontSize: 16, textAlign: "right", writingDirection: "rtl" }, quickRow: { flexDirection: "row", gap: 8 }, shortcut: { flex: 1, minHeight: 89, backgroundColor: colors.surface, borderRadius: radii.md, paddingVertical: 12, paddingHorizontal: 4, alignItems: "center", justifyContent: "center", gap: 8 }, shortcutIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.page, alignItems: "center", justifyContent: "center" }, shortcutLabel: { color: colors.text, fontFamily: fonts.medium, fontSize: 11, textAlign: "center", writingDirection: "rtl" }, notice: { backgroundColor: colors.successSoft, borderRadius: radii.sm, padding: 12, flexDirection: "row", alignItems: "center", gap: 8 }, noticeText: { flex: 1, color: colors.primary, fontFamily: fonts.regular, fontSize: 11, textAlign: "right", writingDirection: "rtl" },
  bottomNav: { height: 80, backgroundColor: colors.page, borderTopWidth: 1, borderColor: colors.border, paddingHorizontal: 16, paddingVertical: 8, flexDirection: "row" }, navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 4 }, navLabel: { color: colors.muted, fontFamily: fonts.regular, fontSize: 11, textAlign: "center", writingDirection: "rtl" }, navActive: { color: colors.accent, fontFamily: fonts.medium },
});
