import Link from "next/link";

const tabs = [["عمومی","/admin/settings"],["ماشین‌حساب","/admin/settings/calculator"],["سایت","/admin/settings/website"],["پیامک","/admin/settings/sms"],["API","/admin/settings/integrations"],["طرح‌های مالی","/admin/settings/financial-products"],["طرح‌های عضویت","/admin/settings/membership-plans"]] as const;
type PageProps = { params: Promise<{ id: string }> };

export default async function AdminIntegrationEditorPage({ params }: PageProps) {
  const { id } = await params;
  const serviceName = id === "bank-tosee-maskan" ? "بانک توسعه مسکن" : decodeURIComponent(id).replaceAll("-", " ");
  return <section className="admin-settings admin-integrations" data-node-id="872:721" data-name="Admin / Settings / Integrations / Connection Editor">
    <header className="admin-settings__header"><h1>تنظیمات</h1><p>مدیریت اتصال سرویس‌ها، Credentialها، Webhookها، تست سلامت و خطاهای API</p></header>
    <nav className="admin-settings__tabs" aria-label="بخش‌های تنظیمات">{tabs.map(([label,href]) => <Link className={`admin-settings__tab${href === "/admin/settings/integrations" ? " admin-settings__tab--active" : ""}`} href={href} key={href}>{label}</Link>)}</nav>
    <section className="admin-settings__panel admin-integrations__selected admin-integrations__editor-page"><div className="admin-settings__panel-heading"><h2>مدیریت اتصال منتخب</h2><p>{serviceName} — Production</p></div><div className="admin-integrations__status-row"><b className="admin-settings__badge admin-settings__badge--success">فعال</b><b className="admin-settings__badge admin-settings__badge--success">اتصال سالم</b><button className="admin-settings__secondary" type="button">تست اتصال</button></div><div className="admin-settings__fields admin-integrations__fields"><label className="admin-integrations__wide"><span>Base URL</span><input dir="ltr" defaultValue="https://api.partner.example/v1" /></label><label><span>روش احراز</span><input dir="ltr" defaultValue="OAuth 2.0 / Client Credentials" /></label><label><span>Timeout / Retry</span><input dir="ltr" defaultValue="15s / 3 retries" /></label><label><span>Client ID</span><input dir="ltr" defaultValue="charkhooneh-prod" /></label><label><span>Client Secret</span><input dir="ltr" defaultValue="••••••••••••••••" readOnly /></label></div><div className="admin-integrations__actions"><button className="admin-integrations__warning" type="button">غیرفعال کردن</button><button className="admin-settings__primary" type="button">ذخیره تغییرات</button></div></section>
    <div className="admin-settings__split"><section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>Credential و Webhook</h2><p>کلیدهای حساس ماسک می‌شوند و تغییرات با زمان ثبت می‌شوند.</p></div><div className="admin-settings__fields admin-integrations__webhook"><label className="admin-integrations__wide"><span>Webhook URL</span><input dir="ltr" defaultValue="https://charkhooneh.ir/api/webhooks/partner" /></label><label><span>Webhook Secret</span><input dir="ltr" defaultValue="••••••••••••" readOnly /></label><label><span>انقضای Credential</span><input defaultValue="۱۴۰۵/۰۷/۱۵" /></label></div><div className="admin-integrations__actions"><button className="admin-settings__secondary" type="button">چرخش کلید</button><button className="admin-settings__primary" type="button">ذخیره Webhook</button></div></section><section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>سلامت و خطاهای اخیر</h2><p>آخرین پاسخ‌ها و خطاهای قابل اقدام برای سرویس منتخب.</p></div><div className="admin-integrations__logs"><div><b className="admin-settings__badge admin-settings__badge--success">200 OK</b><strong>تست اتصال موفق</strong><span>امروز ۱۴:۲۸</span></div><div><b className="admin-settings__badge admin-settings__badge--warning">401</b><strong>توکن منقضی شده؛ Refresh انجام شد</strong><span>امروز ۱۲:۰۴</span></div><div><b className="admin-settings__badge admin-settings__badge--success">Webhook 200</b><strong>Callback پرداخت دریافت شد</strong><span>دیروز ۱۸:۳۲</span></div></div><button className="admin-settings__primary" type="button">تست مجدد</button></section></div>
  </section>;
}
