import Link from "next/link";

const tabs = [["عمومی","/admin/settings"],["ماشین‌حساب","/admin/settings/calculator"],["سایت","/admin/settings/website"],["پیامک","/admin/settings/sms"],["API","/admin/settings/integrations"],["طرح‌های مالی","/admin/settings/financial-products"],["طرح‌های عضویت","/admin/settings/membership-plans"]] as const;
const metrics = [
  { label: "وضعیت سرویس", value: "متصل", note: "آخرین بررسی: ۲ دقیقه پیش" }, { label: "نرخ تحویل امروز", value: "۹۸٫۷٪", note: "۱٬۲۴۶ پیام تحویل‌شده" }, { label: "صف ارسال", value: "۱۲ پیام", note: "در انتظار ارسال" }, { label: "خطاهای امروز", value: "۴ مورد", note: "نیازمند بررسی", danger: true },
] as const;
const templates = [
  { id: "otp-login", name: "OTP ورود", use: "ورود و احراز هویت", sent: "امروز ۱۴:۳۲" }, { id: "case-status", name: "وضعیت پرونده", use: "تغییر مرحله / نیازمند اقدام", sent: "امروز ۱۳:۱۰" }, { id: "payment", name: "پرداخت", use: "موفق / ناموفق / در انتظار", sent: "دیروز ۱۸:۰۵" }, { id: "settlement", name: "تسویه", use: "ثبت یا تکمیل تسویه", sent: "۲ روز پیش" },
] as const;

export default function AdminSmsSettingsPage() {
  return <section className="admin-settings admin-sms" data-node-id="732:166" data-name="Admin / Settings / SMS">
    <header className="admin-settings__header"><h1>تنظیمات</h1><p>مدیریت اتصال سامانه پیامکی، قالب‌ها، سلامت ارسال و پیامک‌های آزمایشی</p></header>
    <nav className="admin-settings__tabs" aria-label="بخش‌های تنظیمات">{tabs.map(([label,href]) => <Link className={`admin-settings__tab${href === "/admin/settings/sms" ? " admin-settings__tab--active" : ""}`} href={href} key={href}>{label}</Link>)}</nav>
    <section className="admin-settings__metrics">{metrics.map((item) => <article key={item.label}><span>{item.label}</span><strong className={item.danger ? "admin-sms__danger" : ""}>{item.value}</strong><small>{item.note}</small></article>)}</section>

    <section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>اتصال و تنظیمات سامانه پیامکی</h2><p>Provider، خط ارسال و Credential را مدیریت کنید. کلید API فقط به‌صورت ماسک‌شده نمایش داده می‌شود.</p></div><div className="admin-settings__fields admin-sms__provider-grid"><label><span>ارائه‌دهنده</span><input defaultValue="کاوه‌نگار" /></label><label><span>شماره / خط ارسال</span><input dir="ltr" defaultValue="1000XXXX" /></label><label><span>API Key</span><input dir="ltr" defaultValue="••••••••••••••••" readOnly /></label><label><span>محیط ارسال</span><input dir="ltr" defaultValue="Production" /></label></div><div className="admin-sms__connection-row"><b className="admin-settings__badge admin-settings__badge--success">اتصال سالم</b><span>آخرین تست اتصال: امروز ۱۴:۲۲ • زمان پاسخ: ۲۱۰ms</span><button className="admin-settings__secondary" type="button">تست اتصال</button><button className="admin-settings__primary" type="button">ذخیره اتصال</button></div></section>

    <div className="admin-sms__columns"><section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>قالب‌های پیامک</h2><p>قالب‌ها، وضعیت و آخرین ارسال را بدون تغییر کد کنترل کنید.</p></div><div className="admin-sms__table"><div className="admin-sms__row admin-sms__row--head"><span>اقدام</span><span>وضعیت</span><span>آخرین ارسال</span><span>کاربرد</span><span>قالب</span></div>{templates.map((item) => <div className="admin-sms__row" key={item.id}><span><Link className="admin-settings__secondary admin-sms__edit" href={`/admin/settings/sms/templates/${item.id}`}>ویرایش</Link></span><span><b className="admin-settings__badge admin-settings__badge--success">فعال</b></span><span>{item.sent}</span><span>{item.use}</span><strong>{item.name}</strong></div>)}</div></section>
      <section className="admin-settings__panel admin-sms__editor"><div className="admin-settings__panel-heading"><h2>ویرایش قالب منتخب</h2><p>نمونه: OTP ورود</p></div><div className="admin-settings__fields"><div className="admin-sms__two"><label><span>کد قالب</span><input dir="ltr" defaultValue="OTP_LOGIN" /></label><label><span>وضعیت</span><input defaultValue="فعال" /></label></div><label><span>متن پیام</span><textarea defaultValue={"کد ورود شما به چارخونه: {{code}}\nاین کد تا {{ttl}} دقیقه معتبر است."} /></label></div><div className="admin-sms__actions"><button className="admin-settings__secondary" type="button">ذخیره پیش‌نویس</button><button className="admin-settings__primary" type="button">ذخیره و فعال‌سازی</button></div></section></div>

    <section className="admin-settings__panel admin-sms__test"><div className="admin-settings__panel-heading"><h2>ارسال پیامک آزمایشی</h2><p>قبل از فعال‌سازی قالب یا تغییر Provider، پیام آزمایشی ارسال و نتیجه Delivery را بررسی کنید.</p></div><div className="admin-sms__test-grid"><label><span>شماره مقصد آزمایشی</span><input defaultValue="۰۹۱۲•••••۶۷" /></label><label><span>قالب</span><input defaultValue="OTP ورود" /></label><label><span>متغیرهای نمونه</span><input dir="ltr" defaultValue="code=482931 / ttl=2" /></label><button className="admin-settings__primary" type="button">ارسال آزمایشی</button></div><div className="admin-sms__test-result"><b className="admin-settings__badge admin-settings__badge--success">آخرین تست: تحویل‌شده</b><span>شناسه ارسال TEST-SMS-1405-231 • تحویل در ۳٫۲ ثانیه</span></div></section>
  </section>;
}
