import Link from "next/link";

const tabs = [["عمومی","/admin/settings"],["ماشین‌حساب","/admin/settings/calculator"],["سایت","/admin/settings/website"],["پیامک","/admin/settings/sms"],["API","/admin/settings/integrations"],["طرح‌های مالی","/admin/settings/financial-products"],["طرح‌های عضویت","/admin/settings/membership-plans"]] as const;
const metrics = [{label:"طرح‌های فعال",value:"۵ طرح",note:"قابل انتخاب در تجربه کاربر"},{label:"پیش‌نویس",value:"۲ طرح",note:"هنوز منتشر نشده‌اند"},{label:"شرکای ارائه‌دهنده",value:"۴ شریک",note:"بانک، صندوق و سازمان"},{label:"نیازمند بازبینی",value:"۱ طرح",note:"شرایط مالی در انتظار تأیید"}] as const;
const products = [
  ["deposit-housing","طرح ودیعه مسکن","بانک توسعه مسکن","۵۰۰ میلیون","۱٫۵٪","CAL-1405-02","فعال","success"],
  ["corporate-rent","طرح اجاره سازمانی","سازمان رفاه کارکنان","۳۰۰ میلیون","توافقی","CAL-1405-01","فعال","success"],
  ["atiye-financing","طرح تأمین مالی آتیه","صندوق مسکن آتیه","۷۰۰ میلیون","۱٫۲٪","CAL-1405-03","فعال","success"],
  ["brokerage-pilot","طرح آزمایشی کارگزاری","کارگزاری سرمایه ایرانیان","۲۵۰ میلیون","۱٫۸٪","CAL-1405-04","پیش‌نویس","neutral"],
  ["urban-housing","طرح مسکن شهری","بانک شهر نمونه","۴۰۰ میلیون","۱٫۴٪","CAL-1405-02","نیازمند بررسی","warning"],
] as const;

export default function AdminFinancialProductAddPage() {
 return <section className="admin-settings admin-financial-products" data-node-id="760:43" data-name="Admin / Settings / Financial Products / Add">
  <header className="admin-settings__header"><h1>تنظیمات</h1><p>تعریف طرح مالی جدید و اتصال آن به شریک، محدودیت‌های مبلغ و Rule ماشین‌حساب</p></header>
  <nav className="admin-settings__tabs">{tabs.map(([label,href])=><Link className={`admin-settings__tab${href==="/admin/settings/financial-products"?" admin-settings__tab--active":""}`} href={href} key={href}>{label}</Link>)}</nav>
  <section className="admin-settings__metrics">{metrics.map(item=><article key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></article>)}</section>
  <div className="admin-financial-products__title-row"><div><h2>طرح‌ها و محصولات مالی</h2><p>شرایط هر طرح، شریک ارائه‌دهنده، محدودیت‌ها و اتصال به ماشین‌حساب را مدیریت کنید.</p></div></div>
  <section className="admin-settings__panel admin-financial-products__table-card"><div className="admin-financial-products__table"><div className="admin-financial-products__row admin-financial-products__row--head"><span>اقدام</span><span>وضعیت</span><span>ماشین‌حساب</span><span>کارمزد</span><span>سقف تأمین</span><span>شریک ارائه‌دهنده</span><span>نام طرح</span></div>{products.map(([id,name,partner,ceiling,fee,calculator,status,tone])=><div className="admin-financial-products__row" key={id}><span><Link className="admin-settings__secondary admin-financial-products__manage" href={`/admin/settings/financial-products/${id}`}>مدیریت</Link></span><span><b className={`admin-settings__badge admin-settings__badge--${tone}`}>{status}</b></span><strong className="admin-financial-products__rule">{calculator}</strong><span>{fee}</span><span>{ceiling}</span><span>{partner}</span><strong>{name}</strong></div>)}</div><p className="admin-financial-products__count">۵ طرح از ۷ طرح ثبت‌شده</p></section>
  <section className="admin-settings__panel admin-financial-products__editor"><div className="admin-financial-products__editor-head"><div><h2>افزودن طرح مالی</h2><p>طرح جدید را تعریف کنید؛ تا زمان انتشار در وضعیت پیش‌نویس باقی می‌ماند.</p></div><div><button className="admin-settings__primary" type="button">ثبت طرح</button><Link className="admin-settings__secondary admin-financial-products__cancel" href="/admin/settings/financial-products">انصراف</Link></div></div><div className="admin-financial-products__field-grid"><article><span>نام طرح</span><input placeholder="نام طرح را وارد کنید" /></article><article><span>شریک ارائه‌دهنده</span><select defaultValue=""><option value="" disabled>انتخاب شریک</option><option>بانک توسعه مسکن</option><option>صندوق مسکن آتیه</option><option>سازمان رفاه کارکنان</option></select></article><article><span>قاعده ماشین‌حساب</span><select defaultValue=""><option value="" disabled>انتخاب Rule</option><option>CAL-1405-01</option><option>CAL-1405-02</option><option>CAL-1405-03</option><option>CAL-1405-04</option></select></article><article><span>وضعیت انتشار</span><strong>پیش‌نویس</strong></article><article><span>حداقل مبلغ</span><input placeholder="حداقل مبلغ" /></article><article><span>حداکثر مبلغ</span><input placeholder="حداکثر مبلغ" /></article><article><span>مدت</span><input placeholder="مثلاً ۱۲ ماه" /></article><article><span>کارمزد</span><input placeholder="مثلاً ۱٫۵٪" /></article></div></section>
 </section>;
}
