import Link from "next/link";

const tabs = [["عمومی","/admin/settings"],["ماشین‌حساب","/admin/settings/calculator"],["سایت","/admin/settings/website"],["پیامک","/admin/settings/sms"],["API","/admin/settings/integrations"],["طرح‌های مالی","/admin/settings/financial-products"],["طرح‌های عضویت","/admin/settings/membership-plans"]] as const;
const metrics = [
  { label: "اتصال‌های فعال", value: "۱۸ سرویس", note: "از ۲۰ اتصال ثبت‌شده" }, { label: "خطاهای امروز", value: "۳ مورد", note: "۲ سرویس نیازمند بررسی", danger: true }, { label: "Webhook ناموفق", value: "۲ مورد", note: "در ۲۴ ساعت گذشته" }, { label: "کلید نزدیک انقضا", value: "۱ Credential", note: "کمتر از ۱۴ روز" },
] as const;
const services = [
  { id: "bank-tosee-maskan", name: "بانک توسعه مسکن", type: "REST API", tested: "امروز ۱۴:۲۸", status: "سالم", tone: "success" },
  { id: "fund-maskane-atiye", name: "صندوق مسکن آتیه", type: "Webhook", tested: "امروز ۱۳:۵۵", status: "هشدار", tone: "warning" },
  { id: "brokerage-sarmaye-iranian", name: "کارگزاری سرمایه ایرانیان", type: "REST API", tested: "امروز ۱۲:۴۰", status: "سالم", tone: "success" },
  { id: "identity-service", name: "سرویس احراز هویت", type: "REST API", tested: "امروز ۱۴:۱۰", status: "خطا", tone: "danger" },
  { id: "sms-service", name: "سامانه پیامکی", type: "REST API", tested: "امروز ۱۴:۳۲", status: "سالم", tone: "success" },
] as const;

function SelectedIntegration() { return <section className="admin-settings__panel admin-integrations__selected"><div className="admin-settings__panel-heading"><h2>مدیریت اتصال منتخب</h2><p>بانک توسعه مسکن — Production</p></div><div className="admin-integrations__status-row"><b className="admin-settings__badge admin-settings__badge--success">فعال</b><b className="admin-settings__badge admin-settings__badge--success">اتصال سالم</b><button className="admin-settings__secondary" type="button">تست اتصال</button></div><div className="admin-settings__fields admin-integrations__fields"><label className="admin-integrations__wide"><span>Base URL</span><input dir="ltr" defaultValue="https://api.partner.example/v1" /></label><label><span>روش احراز</span><input dir="ltr" defaultValue="OAuth 2.0 / Client Credentials" /></label><label><span>Timeout / Retry</span><input dir="ltr" defaultValue="15s / 3 retries" /></label><label><span>Client ID</span><input dir="ltr" defaultValue="charkhooneh-prod" /></label><label><span>Client Secret</span><input dir="ltr" defaultValue="••••••••••••••••" readOnly /></label></div><div className="admin-integrations__actions"><button className="admin-integrations__warning" type="button">غیرفعال کردن</button><button className="admin-settings__primary" type="button">ذخیره تغییرات</button></div></section>; }

export default function AdminIntegrationsPage() {
  return <section className="admin-settings admin-integrations" data-node-id="732:243" data-name="Admin / Settings / Integrations">
    <header className="admin-settings__header"><h1>تنظیمات</h1><p>مدیریت اتصال سرویس‌ها، Credentialها، Webhookها، تست سلامت و خطاهای API</p></header>
    <nav className="admin-settings__tabs" aria-label="بخش‌های تنظیمات">{tabs.map(([label,href]) => <Link className={`admin-settings__tab${href === "/admin/settings/integrations" ? " admin-settings__tab--active" : ""}`} href={href} key={href}>{label}</Link>)}</nav>
    <section className="admin-settings__metrics">{metrics.map((item) => <article key={item.label}><span>{item.label}</span><strong className={"danger" in item && item.danger ? "admin-integrations__danger" : ""}>{item.value}</strong><small>{item.note}</small></article>)}</section>
    <div className="admin-integrations__columns"><section className="admin-settings__panel admin-integrations__list"><div className="admin-settings__panel-heading"><h2>اتصال‌های سرویس</h2><p>وضعیت، محیط و آخرین تست اتصال هر سرویس را از همین‌جا کنترل کنید.</p></div><div className="admin-integrations__table"><div className="admin-integrations__row admin-integrations__row--head"><span>اقدام</span><span>سلامت</span><span>آخرین تست</span><span>نوع</span><span>سرویس</span></div>{services.map((item) => <div className="admin-integrations__row" key={item.id}><span><Link className="admin-settings__secondary admin-integrations__manage" href={`/admin/settings/integrations/${item.id}`}>مدیریت</Link></span><span><b className={`admin-settings__badge admin-settings__badge--${item.tone}`}>{item.status}</b></span><span>{item.tested}</span><span>{item.type}</span><strong>{item.name}</strong></div>)}</div><div className="admin-integrations__list-footer"><button className="admin-settings__primary" type="button">افزودن اتصال</button><span>۵ اتصال از ۲۰ اتصال ثبت‌شده</span></div></section><SelectedIntegration /></div>
    <div className="admin-settings__split"><section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>Credential و Webhook</h2><p>کلیدهای حساس ماسک می‌شوند و تغییرات با زمان ثبت می‌شوند.</p></div><div className="admin-settings__fields admin-integrations__webhook"><label className="admin-integrations__wide"><span>Webhook URL</span><input dir="ltr" defaultValue="https://charkhooneh.ir/api/webhooks/partner" /></label><label><span>Webhook Secret</span><input dir="ltr" defaultValue="••••••••••••" readOnly /></label><label><span>انقضای Credential</span><input defaultValue="۱۴۰۵/۰۷/۱۵" /></label></div><div className="admin-integrations__actions"><button className="admin-settings__secondary" type="button">چرخش کلید</button><button className="admin-settings__primary" type="button">ذخیره Webhook</button></div></section><section className="admin-settings__panel"><div className="admin-settings__panel-heading"><h2>سلامت و خطاهای اخیر</h2><p>آخرین پاسخ‌ها و خطاهای قابل اقدام برای سرویس منتخب.</p></div><div className="admin-integrations__logs"><div><b className="admin-settings__badge admin-settings__badge--success">200 OK</b><strong>تست اتصال موفق</strong><span>امروز ۱۴:۲۸</span></div><div><b className="admin-settings__badge admin-settings__badge--warning">401</b><strong>توکن منقضی شده؛ Refresh انجام شد</strong><span>امروز ۱۲:۰۴</span></div><div><b className="admin-settings__badge admin-settings__badge--success">Webhook 200</b><strong>Callback پرداخت دریافت شد</strong><span>دیروز ۱۸:۳۲</span></div></div><button className="admin-settings__primary" type="button">تست مجدد</button></section></div>
  </section>;
}
