// <auto-generated />
using System;
using Charkhoone.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Charkhoone.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CharkhooneDbContext))]
    [Migration("20260917152215_AddDatabaseIntegrityEnforcementV2")]
    partial class AddDatabaseIntegrityEnforcementV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.AuditEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc", "Id");

                    b.HasIndex("AggregateType", "AggregateId", "Action", "OccurredAtUtc", "Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankApprovalRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedLoanRial")
                        .HasColumnType("numeric");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("MaximumEligibleLoanRial")
                        .HasColumnType("numeric");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreditApplicationId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("bank_approvals", null, t =>
                        {
                            t.HasCheckConstraint("CK_bank_approvals_amounts_valid", "\"MaximumEligibleLoanRial\" >= 0 AND \"MaximumEligibleLoanRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND (\"ApprovedLoanRial\" IS NULL OR (\"ApprovedLoanRial\" >= 0 AND \"ApprovedLoanRial\" <= \"MaximumEligibleLoanRial\" AND \"ApprovedLoanRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')))");

                            t.HasCheckConstraint("CK_bank_approvals_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankLoanPlanOrganizationRow", b =>
                {
                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("PlanVersionId", "OrganizationId");

                    b.ToTable("bank_loan_plan_organizations", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankLoanPlanVersionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InterestTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TermMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Version")
                        .IsUnique();

                    b.ToTable("bank_loan_plan_versions", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CancellationSettlementRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RemainingTenantContributionRial")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("cancellation_settlements", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.ContractDelinquencyRow", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CancellationRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("ConsecutiveMissedMonths")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContractId");

                    b.ToTable("contract_delinquencies", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CoveragePaymentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MonthlyObligationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentInstructionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RemainingTenantContributionRial")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.HasIndex("PaymentInstructionId")
                        .IsUnique();

                    b.HasIndex("ContractId", "Status");

                    b.HasIndex("MonthlyObligationId", "Status");

                    b.ToTable("coverage_payments", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankLoanPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankLoanPlanVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditGradePolicyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.ToTable("credit_applications", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditEligibilityAssessmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSubGrade")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("FullDepositEquivalentRial")
                        .HasColumnType("numeric");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("LoanRatio")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal?>("MaximumEligibleLoanRial")
                        .HasColumnType("numeric");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreditApplicationId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("credit_eligibility_assessments", null, t =>
                        {
                            t.HasCheckConstraint("CK_credit_eligibility_assessments_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditGradePolicyEntryRow", b =>
                {
                    b.Property<Guid>("PolicyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSubGrade")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("LoanRatio")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.HasKey("PolicyVersionId", "ExternalSubGrade");

                    b.ToTable("credit_grade_policy_entries", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditGradePolicyVersionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("credit_grade_policy_versions", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc", "Id")
                        .HasFilter("\"AggregateType\" = 'PaymentInstruction' AND \"OperationType\" = 'payment_reconciliation' AND \"Status\" IN ('Pending','Unknown')");

                    b.HasIndex("AggregateType", "AggregateId", "CreatedAtUtc");

                    b.HasIndex("AggregateType", "AggregateId", "UpdatedAtUtc", "Id");

                    b.ToTable("external_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_external_transactions_amount_positive_finite", "\"AmountRial\" > 0 AND \"AmountRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");

                            t.HasCheckConstraint("CK_external_transactions_currency_irr", "\"Currency\" = 'IRR'");

                            t.HasCheckConstraint("CK_external_transactions_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FrozenPrincipalRow", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("FrozenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FundReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ContractId");

                    b.ToTable("frozen_principals", null, t =>
                        {
                            t.HasCheckConstraint("CK_frozen_principals_amount_positive_finite", "\"AmountRial\" > 0 AND \"AmountRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FundPrincipalFreezeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FundReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("FundingAllocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FundingAllocationId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("fund_principal_freezes", null, t =>
                        {
                            t.HasCheckConstraint("CK_fund_principal_freezes_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BankApprovedLoanRial")
                        .HasColumnType("numeric");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("BankLoanPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankLoanPlanVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FullDepositEquivalentRial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaximumEligibleLoanRial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TenantContributionRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("CreditApplicationId")
                        .IsUnique();

                    b.ToTable("funding_allocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_funding_allocations_amounts_and_equation", "\"FullDepositEquivalentRial\" >= 0 AND \"MaximumEligibleLoanRial\" >= 0 AND \"BankApprovedLoanRial\" >= 0 AND \"TenantContributionRial\" >= 0 AND \"BankApprovedLoanRial\" <= \"MaximumEligibleLoanRial\" AND \"BankApprovedLoanRial\" <= \"FullDepositEquivalentRial\" AND \"BankApprovedLoanRial\" + \"TenantContributionRial\" = \"FullDepositEquivalentRial\" AND \"FullDepositEquivalentRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND \"MaximumEligibleLoanRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND \"BankApprovedLoanRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND \"TenantContributionRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.InboxMessageRow", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ReversalOfJournalEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReversalOfJournalEntryId");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.ToTable("journal_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_journal_entries_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");

                            t.HasCheckConstraint("CK_journal_entries_not_self_reversal", "\"ReversalOfJournalEntryId\" IS NULL OR \"ReversalOfJournalEntryId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_journal_entries_posted_at_or_after_occurred_at", "\"PostedAtUtc\" >= \"OccurredAtUtc\"");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalEntrySealRow", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SealedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCreditRial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebitRial")
                        .HasColumnType("numeric");

                    b.HasKey("JournalEntryId");

                    b.ToTable("journal_entry_seals", null, t =>
                        {
                            t.HasCheckConstraint("CK_journal_entry_seals_balanced_positive_finite", "\"LineCount\" >= 2 AND \"TotalDebitRial\" > 0 AND \"TotalCreditRial\" > 0 AND \"TotalDebitRial\" = \"TotalCreditRial\" AND \"TotalDebitRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND \"TotalCreditRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditRial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DebitRial")
                        .HasColumnType("numeric");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("LedgerAccountId");

                    b.ToTable("journal_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_journal_lines_single_sided_positive_finite", "\"DebitRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND \"CreditRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity') AND ((\"DebitRial\" > 0 AND \"CreditRial\" = 0) OR (\"CreditRial\" > 0 AND \"DebitRial\" = 0))");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankLoanPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankLoanPlanVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreditApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreditGradePolicyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreditApplicationId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantUserId");

                    b.HasIndex("Status", "UpdatedAtUtc", "Id");

                    b.ToTable("lease_contracts", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LedgerAccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ContractId");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ledger_accounts_currency_irr", "\"Currency\" = 'IRR'");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LostFundReturnRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CalculatedReturnRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CalculationPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CalculationPeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculationPolicyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoveragePaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<DateTimeOffset?>("ReplacedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WithdrawnAmountRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("WithdrawnAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasFilter("\"CalculatedReturnRial\" IS NULL");

                    b.HasIndex("CoveragePaymentId")
                        .IsUnique();

                    b.HasIndex("ContractId", "WithdrawnAtUtc");

                    b.ToTable("lost_fund_returns", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationComponentRow", b =>
                {
                    b.Property<Guid>("PaymentInstructionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MonthlyObligationId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentInstructionId");

                    b.HasIndex("MonthlyObligationId", "Kind")
                        .IsUnique();

                    b.ToTable("monthly_obligation_components", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractMonthNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "ContractMonthNumber")
                        .IsUnique();

                    b.HasIndex("Status", "DueAtUtc", "Id");

                    b.ToTable("monthly_obligations", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.NormalSettlementRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("BankExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("BankJournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BankPrincipalAmountRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BankPrincipalReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BankPrincipalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FundReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("TenantExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantJournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TenantResidualAmountRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("TenantResidualReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantResidualStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("BankJournalEntryId")
                        .IsUnique();

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("TenantExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("TenantJournalEntryId")
                        .IsUnique();

                    b.HasIndex("TenantUserId");

                    b.ToTable("normal_settlements", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.OutboxMessageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.PaymentInstructionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ObligationId");

                    b.ToTable("payment_instructions", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_instructions_amount_positive_finite", "\"AmountRial\" > 0 AND \"AmountRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");

                            t.HasCheckConstraint("CK_payment_instructions_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionFundingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FundReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("FundingAllocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("FundingAllocationId")
                        .IsUnique();

                    b.ToTable("tenant_contribution_fundings", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionReplenishmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountRial")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ExternalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RemainingTenantContributionRial")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ReplenishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("JournalEntryId")
                        .IsUnique();

                    b.HasIndex("ContractId", "ReplenishedAtUtc");

                    b.ToTable("tenant_contribution_replenishments", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionRow", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("FundReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("FundedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FundingAllocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialAmountRial")
                        .HasColumnType("numeric");

                    b.HasKey("ContractId");

                    b.HasIndex("FundingAllocationId")
                        .IsUnique();

                    b.ToTable("tenant_contributions", null, t =>
                        {
                            t.HasCheckConstraint("CK_tenant_contributions_initial_amount_positive_finite", "\"InitialAmountRial\" > 0 AND \"InitialAmountRial\"::text NOT IN ('NaN', 'Infinity', '-Infinity')");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.UserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OidcSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.VerificationRequestRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CreditApplicationId", "Type", "CreatedAtUtc");

                    b.ToTable("verification_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_verification_requests_idempotency_key_nonblank", "btrim(\"IdempotencyKey\") <> ''");
                        });
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.WorkflowTransitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAtUtc");

                    b.ToTable("workflow_transitions", (string)null);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankApprovalRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.BankApprovalRow", "CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankLoanPlanOrganizationRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.BankLoanPlanVersionRow", null)
                        .WithMany("AllowedOrganizations")
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CancellationSettlementRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.CancellationSettlementRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.CancellationSettlementRow", "ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.UserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.ContractDelinquencyRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.ContractDelinquencyRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CoveragePaymentRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.CoveragePaymentRow", "ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationRow", null)
                        .WithMany()
                        .HasForeignKey("MonthlyObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.PaymentInstructionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.CoveragePaymentRow", "PaymentInstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.UserRow", null)
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditEligibilityAssessmentRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.CreditEligibilityAssessmentRow", "CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditGradePolicyEntryRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditGradePolicyVersionRow", null)
                        .WithMany("Entries")
                        .HasForeignKey("PolicyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FrozenPrincipalRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.FrozenPrincipalRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FundPrincipalFreezeRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.FundPrincipalFreezeRow", "FundingAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", "CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalEntrySealRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.JournalEntrySealRow", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.JournalLineRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LedgerAccountRow", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", "CreditApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.UserRow", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.UserRow", null)
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LedgerAccountRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.LostFundReturnRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CoveragePaymentRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.LostFundReturnRow", "CoveragePaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationComponentRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationRow", null)
                        .WithMany()
                        .HasForeignKey("MonthlyObligationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.PaymentInstructionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationComponentRow", "PaymentInstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.NormalSettlementRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.NormalSettlementRow", "BankExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("BankJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.NormalSettlementRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.NormalSettlementRow", "TenantExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("TenantJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.UserRow", null)
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.PaymentInstructionRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.MonthlyObligationRow", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionFundingRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.TenantContributionFundingRow", "ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.TenantContributionFundingRow", "FundingAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionReplenishmentRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.ExternalTransactionRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.TenantContributionReplenishmentRow", "ExternalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.TenantContributionRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.LeaseContractRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.TenantContributionRow", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.FundingAllocationRow", null)
                        .WithOne()
                        .HasForeignKey("Charkhoone.Infrastructure.Persistence.Models.TenantContributionRow", "FundingAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.VerificationRequestRow", b =>
                {
                    b.HasOne("Charkhoone.Infrastructure.Persistence.Models.CreditApplicationRow", null)
                        .WithMany()
                        .HasForeignKey("CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.BankLoanPlanVersionRow", b =>
                {
                    b.Navigation("AllowedOrganizations");
                });

            modelBuilder.Entity("Charkhoone.Infrastructure.Persistence.Models.CreditGradePolicyVersionRow", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
